-- VIEW_USER_INFORMATION
CREATE VIEW VIEW_USER_INFORMATION (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE)
AS 
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, 
	CC.CITY_NAME, CC.STATE_NAME, CC.COUNTRY_NAME, HC.CITY_NAME, HC.STATE_NAME, HC.COUNTRY_NAME, E.INSTITUTION, E.PROGRAM_YEAR, E.CONCENTRATION, E.DEGREE
FROM 
(SELECT HC.USER_ID AS USER_ID, C1.CITY_NAME AS CITY_NAME, C1.STATE_NAME AS STATE_NAME, C1.COUNTRY_NAME AS COUNTRY_NAME FROM USER_HOMETOWN_CITY HC LEFT JOIN CITIES C1 ON C1.CITY_ID = HC.HOMETOWN_CITY_ID) HC,
(SELECT CC.USER_ID AS USER_ID, C2.CITY_NAME AS CITY_NAME, C2.STATE_NAME AS STATE_NAME, C2.COUNTRY_NAME AS COUNTRY_NAME FROM USER_CURRENT_CITY CC LEFT JOIN CITIES C2 ON C2.CITY_ID = CC.CURRENT_CITY_ID) CC,
USERS U LEFT JOIN
(SELECT E.USER_ID AS USER_ID, P.INSTITUTION AS INSTITUTION, E.PROGRAM_YEAR AS PROGRAM_YEAR, P.CONCENTRATION AS CONCENTRATION, P.DEGREE AS DEGREE FROM 
	(SELECT E.USER_ID AS USER_ID, E.PROGRAM_ID AS PROGRAM_ID, E.PROGRAM_YEAR AS PROGRAM_YEAR FROM USERS U LEFT JOIN EDUCATION E ON U.USER_ID = E.USER_ID)E
LEFT JOIN PROGRAMS P ON P.PROGRAM_ID = E.PROGRAM_ID)E ON U.USER_ID = E.USER_ID
WHERE U.USER_ID = HC.USER_ID AND U.USER_ID = CC.USER_ID;

-- VIEW_ARE_FRIENDS
CREATE VIEW VIEW_ARE_FRIENDS (USER1_ID, USER2_ID)
AS SELECT DISTINCT F.USER1_ID, F.USER2_ID
FROM FRIENDS F;

-- VIEW_PHOTO_INFORMATION
CREATE VIEW VIEW_PHOTO_INFORMATION (ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
AS SELECT DISTINCT A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM ALBUMS A, PHOTOS P
WHERE A.ALBUM_ID = P.ALBUM_ID;

-- VIEW_TAG_INFORMATION
CREATE VIEW VIEW_TAG_INFORMATION (PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE)
AS SELECT DISTINCT T.TAG_PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, T.TAG_X, T.TAG_Y
FROM TAGS T;

-- VIEW_EVENT_INFORMATION
CREATE VIEW VIEW_EVENT_INFORMATION (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME)
AS SELECT DISTINCT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_LOCATION, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM USER_EVENTS E, CITIES C
WHERE E.EVENT_CITY_ID = C.CITY_ID;