DROP TRIGGER check_order

DROP SEQUENCE city_sequence;
DROP TRIGGER INI_CITY_ID;

DROP SEQUENCE program_sequence;
DROP TRIGGER INI_PROGRAM_ID;

DROP TABLE TAGS;

ALTER TABLE ALBUMS DROP CONSTRAINT COVER_CONSTRAINT;
ALTER TABLE ALBUMS DROP COLUMN COVER_PHOTO_ID;

DROP TABLE PHOTOS;

DROP TABLE ALBUMS;

DROP TABLE PARTICIPANTS;

DROP TABLE USER_EVENTS;

DROP TABLE EDUCATION;

DROP TABLE PROGRAMS;

DROP TABLE MESSAGE;

DROP TABLE USER_HOMETOWN_CITY;

DROP TABLE USER_CURRENT_CITY;
DROP TABLE CITIES;

DROP TABLE FRIENDS;
DROP TABLE USERS;